services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1001}
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
    entrypoint: bash docker/entrypoint.sh